// CATEGORIES
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";
export const GET_CATEGORIES_ERROR = "GET_CATEGORIES_ERROR";

// TOP 10
export const GET_TOPTEN_SUCCESS = "GET_TOPTEN_SUCCESS";
export const GET_TOPTEN_ERROR = "GET_TOPTEN_ERROR";
